name: Hospital pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hsp:
    runs-on: self-hosted
    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: Docker Version display
        run: |
          sudo docker --version
          sudo docker info
      - name: Prune all docker images and containers
        run: |
          sudo docker stop $(docker ps)
          sudo docker prune -a -f
      - name: Docker image creation
        run: | 
          sudo docker build -t hsp:latest .

      - name: Docker images verification
        run: |
          sudo docker images

      - name: Docker Container creation
        run: |
          sudo docker run -d -p 5000:5000 hsp:latest
          
      - name: Docker Container Verification
        run: |
          sudo docker ps -a 
          
      
